MuCAI Blog Post - Update about Prof. Eugene
iFetch-chatbot/ifetch-chatbot.github.io pull request #29
Opened 2021-07-21 10:57 UTC by rjgsousa

Blog entry about MuCAI Call for Papers and Professor Eugene talk.

@cajosantiago and @davidfsemedo can you review?

2021-07-21 17:11 UTC, cajosantiago requested changes
After "updating the keynote speaker: Professor Eugene Agichtein", we should provide a brief description of his profile / biography / track record, highlighting why he is an exceptional guest and why everyone should attend the event.

Source for inspiration (taken from his home page):
Eugene Agichtein is a Winship Associate Professor in the Computer Science department at Emory University. Dr. Agichtein founded and leads the Emory Intelligent Information Access Laboratory (IR Lab). Eugene's general research interests are in web search and information retrieval, conversational search, and more generally in text and data mining, social media analysis, and human-computer interaction. Eugene received a Ph.D. in Computer Science from Columbia University, and a B.S. in Engineering from The Cooper Union. Eugene was a Sloan Research Fellow, a past member of the DARPA Computer Science Study Group, and a recipient of four best paper awards from SIGMOD, SIGIR, WSDM, and ICDE conferences, and test-of-time awards from WSDM and SIGIR. His work has been supported by grants from DARPA, IARPA, the National Institutes of Health, and the National Science Foundation, and by gifts and grants from industry, including Amazon, Google, Home Depot, HP Labs, Microsoft, and Yahoo! Labs. Since January 2019, Dr. Agichtein has been a part-time "Amazon Scholar" (Principal Scientist) at Amazon Alexa.

2021-07-21 19:00 UTC, davidfsemedo reviewed
I agree with @cajosantiago comment about adding the biography of the keynote speaker. 

Also, is the talk topic already defined? If so, we could add something like "Professor Eugene ... will talk about XXX and explain how YYY.

2021-07-21 19:35 UTC, rjgsousa commented
> I agree with @cajosantiago comment about adding the biography of the keynote speaker. 
> 
> Also, is the talk topic already defined? If so, we could add something like "Professor Eugene ... will talk about XXX and explain how YYY.

Thanks for the feedback,  @davidfsemedo 
Let me try to find out which topic he will talk about.

2021-07-21 19:36 UTC, rjgsousa commented
> After "updating the keynote speaker: Professor Eugene Agichtein", we should provide a brief description of his profile / biography / track record, highlighting why he is an exceptional guest and why everyone should attend the event.
> 
> Source for inspiration (taken from his home page):
> Eugene Agichtein is a Winship Associate Professor in the Computer Science department at Emory University. Dr. Agichtein founded and leads the Emory Intelligent Information Access Laboratory (IR Lab). Eugene's general research interests are in web search and information retrieval, conversational search, and more generally in text and data mining, social media analysis, and human-computer interaction. Eugene received a Ph.D. in Computer Science from Columbia University, and a B.S. in Engineering from The Cooper Union. Eugene was a Sloan Research Fellow, a past member of the DARPA Computer Science Study Group, and a recipient of four best paper awards from SIGMOD, SIGIR, WSDM, and ICDE conferences, and test-of-time awards from WSDM and SIGIR. His work has been supported by grants from DARPA, IARPA, the National Institutes of Health, and the National Science Foundation, and by gifts and grants from industry, including Amazon, Google, Home Depot, HP Labs, Microsoft, and Yahoo! Labs. Since January 2019, Dr. Agichtein has been a part-time "Amazon Scholar" (Principal Scientist) at Amazon Alexa.

Awesome. This is very helpful. Thanks so much @cajosantiago !

2021-07-22 10:01 UTC, rjgsousa commented on content/english/blog/blog-post-20210721.md
> +In this blog post, we update the keynote speaker: Professor [Eugene Agichtein](https://scholar.google.com/citations?hl=en&user=3BX3vWcAAAAJ&view_op=list_works&sortby=pubdate). We are delighted to hav
fixed in 5db43a5 thx

2021-07-22 16:52 UTC, cajosantiago approved these changes

2021-07-23 08:13 UTC, merged